import type { Project, ProjectTier } from './types';

// Portfolio project catalog for the learning roadmap.
// Plain ESM, no imports; consumed by app pages and the roadmap views.

export const PROJECT_TIERS: Record<ProjectTier, { label: string; blurb: string }> = {
  starter: { label: 'Starter', blurb: 'Weekend-sized. Proves you can wire the pieces together.' },
  core: { label: 'Core', blurb: 'One to two weeks. The projects interviewers ask about.' },
  flagship: { label: 'Flagship', blurb: 'Multi-week. A production-grade centerpiece for your portfolio.' },
};

export const PROJECTS: Project[] = [
  // ---------- AI / agentic ----------
  {
    id: 'streaming-chat',
    name: 'Streamline Chat',
    tier: 'starter',
    tracks: ['swe'],
    hours: 10,
    pitch: 'A chat app that streams tokens to the browser as they arrive, with conversation history and a stop button that actually cancels the request.',
    proves: [
      'Calling an LLM API directly',
      'Server-sent events and streaming UI',
      'Conversation state management',
      'Request cancellation and error handling',
    ],
    stack: ['Next.js', 'Vercel AI SDK', 'Anthropic API', 'Tailwind'],
    milestones: [
      'Send a single prompt to the API and render the full response',
      'Switch to streaming and render tokens as they arrive',
      'Add multi-turn history with a system prompt',
      'Add stop, retry, and visible error states',
      'Persist conversations to localStorage and deploy',
    ],
    stretch: 'Add a model picker and show per-message token counts and cost.',
    res: [
      { t: 'Vercel AI SDK docs', u: 'https://ai-sdk.dev/docs/introduction' },
      { t: 'Anthropic API overview', u: 'https://docs.anthropic.com/en/api/overview' },
    ],
  },
  {
    id: 'structured-extractor',
    name: 'FormFill',
    tier: 'starter',
    tracks: ['swe'],
    hours: 12,
    pitch: 'Paste messy text (an email thread, a resume, a receipt) and get back schema-validated JSON, with retries when the model output fails validation.',
    proves: [
      'Structured output from an LLM',
      'Schema validation with Zod',
      'Retry loops on invalid output',
      'Prompting for extraction accuracy',
    ],
    stack: ['Next.js', 'Vercel AI SDK', 'Zod', 'Anthropic API'],
    milestones: [
      'Define a target schema (e.g. invoice: vendor, date, line items, total)',
      'Get the model to emit JSON matching the schema via tool use or structured output',
      'Validate with Zod and re-prompt with the validation error on failure',
      'Build a paste-in UI showing raw text next to extracted fields',
      'Test against 20 messy real-world samples and record the pass rate',
    ],
    stretch: 'Support three schemas and auto-detect which one the input matches.',
    res: [
      { t: 'AI SDK structured data', u: 'https://ai-sdk.dev/docs/ai-sdk-core/generating-structured-data' },
      { t: 'Anthropic tool use', u: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/overview' },
    ],
  },
  {
    id: 'docs-rag-chat',
    name: 'DocTalk',
    tier: 'core',
    tracks: ['swe', 'scratch'],
    hours: 30,
    pitch: 'Chat with your own documents: upload PDFs, ask questions, and get answers with inline citations that link back to the exact source chunk.',
    proves: [
      'Chunking and embedding pipelines',
      'Vector search with pgvector',
      'Grounded answers with citations',
      'Handling "not in the docs" honestly',
    ],
    stack: ['Next.js', 'Postgres', 'pgvector', 'Anthropic API', 'Vercel AI SDK'],
    milestones: [
      'Build an ingest script: parse PDFs, chunk by headings, embed, store in pgvector',
      'Implement top-k retrieval and stuff results into the prompt',
      'Force citations: every claim carries a chunk id the UI renders as a link',
      'Return "I could not find this in your documents" when retrieval scores are low',
      'Add upload UI with ingest progress and per-document delete',
      'Deploy with a seeded demo corpus so reviewers can try it instantly',
    ],
    stretch: 'Add contextual chunk headers at ingest time and measure the retrieval improvement.',
    res: [
      { t: 'pgvector', u: 'https://github.com/pgvector/pgvector' },
      { t: 'Contextual retrieval', u: 'https://www.anthropic.com/news/contextual-retrieval' },
      { t: 'LlamaIndex docs', u: 'https://docs.llamaindex.ai/' },
    ],
  },
  {
    id: 'hybrid-search-upgrade',
    name: 'RetrievalBench',
    tier: 'core',
    tracks: ['swe', 'prod'],
    hours: 25,
    pitch: 'Upgrade a basic RAG pipeline to hybrid search plus a reranker, and prove the gain with a side-by-side eval instead of vibes.',
    proves: [
      'Hybrid dense plus keyword search',
      'Cross-encoder reranking',
      'Building a retrieval eval set',
      'Making changes measurable',
    ],
    stack: ['Qdrant', 'Cohere Rerank', 'Ragas', 'Python or Node'],
    milestones: [
      'Stand up a baseline: dense-only retrieval over a fixed corpus',
      'Write a 50-question eval set with known source passages',
      'Add BM25 alongside dense vectors and fuse results',
      'Add a reranker stage over the fused top 20',
      'Run baseline vs hybrid vs hybrid-plus-rerank and report recall and answer quality',
      'Write up the results table with cost and latency per configuration',
    ],
    stretch: 'Add query rewriting and measure whether it helps or hurts each configuration.',
    res: [
      { t: 'Qdrant docs', u: 'https://qdrant.tech/documentation/' },
      { t: 'Cohere rerank', u: 'https://docs.cohere.com/docs/rerank-overview' },
      { t: 'Ragas docs', u: 'https://docs.ragas.io/' },
    ],
  },
  {
    id: 'bare-metal-agent',
    name: 'Loopsmith',
    tier: 'starter',
    tracks: ['scratch', 'swe'],
    hours: 14,
    pitch: 'An agent loop written by hand in under 300 lines: no framework, two real tools, and a transcript log that shows every step of its reasoning.',
    proves: [
      'The core agent loop: model, tools, results, repeat',
      'Tool schema design',
      'Stop conditions and max-iteration guards',
      'Reading raw API responses',
    ],
    stack: ['Node.js or Python', 'Anthropic API'],
    milestones: [
      'Write the bare loop: send messages, detect tool_use blocks, execute, append results',
      'Implement two tools: a calculator and a web fetch (or file read)',
      'Add a max-iterations guard and a clean final-answer stop condition',
      'Log every request and response to a JSONL transcript',
      'Run 10 multi-step tasks and annotate where the loop succeeds and fails',
    ],
    stretch: 'Add a scratchpad tool the agent uses to plan before acting, and compare transcripts.',
    res: [
      { t: 'Building effective agents', u: 'https://www.anthropic.com/research/building-effective-agents' },
      { t: 'Anthropic tool use', u: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/overview' },
    ],
  },
  {
    id: 'langgraph-research-agent',
    name: 'DeskResearcher',
    tier: 'core',
    tracks: ['swe'],
    hours: 30,
    pitch: 'A research agent built as an explicit LangGraph state machine: it plans, searches, drafts a report, and pauses for human approval before publishing.',
    proves: [
      'Graph-based agent orchestration',
      'Human-in-the-loop interrupts',
      'Checkpointing and resumable state',
      'Structured multi-step workflows',
    ],
    stack: ['LangGraph', 'Python', 'Anthropic API', 'SQLite checkpointer'],
    milestones: [
      'Model the workflow as nodes: plan, search, synthesize, review, publish',
      'Implement the plan and search nodes with a web search tool',
      'Add a synthesize node that drafts a cited report from collected sources',
      'Insert an interrupt before publish; resume from the checkpoint after approval or edits',
      'Add a CLI or minimal UI to review pending reports and approve or reject',
      'Handle rejection: route feedback back into the plan node and regenerate',
    ],
    stretch: 'Persist checkpoints to Postgres so runs survive process restarts.',
    res: [
      { t: 'LangGraph docs', u: 'https://langchain-ai.github.io/langgraph/' },
      { t: 'Human-in-the-loop', u: 'https://langchain-ai.github.io/langgraph/concepts/human_in_the_loop/' },
    ],
  },
  {
    id: 'mcp-api-server',
    name: 'BridgeMCP',
    tier: 'starter',
    tracks: ['swe', 'prod'],
    hours: 12,
    pitch: 'An MCP server that wraps a real public API (weather, GitHub, transit) so any MCP client, including Claude, can call it as native tools.',
    proves: [
      'The MCP protocol: tools, resources, transports',
      'Wrapping a REST API as typed tools',
      'Input validation and error surfaces',
      'Testing against a real client',
    ],
    stack: ['TypeScript', 'MCP SDK', 'Zod', 'a public REST API'],
    milestones: [
      'Scaffold a stdio MCP server with one hello tool and connect it to a client',
      'Wrap three API endpoints as tools with Zod-validated inputs',
      'Return structured, model-friendly errors for bad input and API failures',
      'Add one resource (e.g. cached reference data) alongside the tools',
      'Write a README with client config snippets and record a short demo',
    ],
    stretch: 'Add an HTTP transport and deploy the server so remote clients can use it.',
    res: [
      { t: 'Model Context Protocol', u: 'https://modelcontextprotocol.io/' },
      { t: 'GitHub', u: 'https://github.com/' },
    ],
  },
  {
    id: 'multi-agent-supervisor',
    name: 'CrewDesk',
    tier: 'flagship',
    tracks: ['swe', 'prod'],
    hours: 45,
    pitch: 'A supervisor agent that decomposes a task and delegates to two or three specialist agents (researcher, coder, reviewer), with traces that show who did what.',
    proves: [
      'Supervisor and worker orchestration',
      'Task decomposition and delegation',
      'Context isolation between agents',
      'Tracing multi-agent runs',
    ],
    stack: ['LangGraph', 'Anthropic API', 'Langfuse', 'Python'],
    milestones: [
      'Build two specialists as standalone agents with their own tools and prompts',
      'Add a supervisor that routes subtasks and merges results',
      'Isolate contexts: workers see only their subtask, not the whole conversation',
      'Instrument every agent call with Langfuse traces',
      'Run 15 tasks; compare against a single-agent baseline on quality and cost',
      'Write up when the multi-agent setup wins and when it just burns tokens',
    ],
    stretch: 'Let the supervisor spawn workers in parallel and merge concurrent results.',
    res: [
      { t: 'Multi-agent research system', u: 'https://www.anthropic.com/engineering/built-multi-agent-research-system' },
      { t: 'LangGraph docs', u: 'https://langchain-ai.github.io/langgraph/' },
      { t: 'Langfuse docs', u: 'https://langfuse.com/docs' },
    ],
  },
  {
    id: 'eval-harness-ci',
    name: 'JudgeGate',
    tier: 'core',
    tracks: ['prod', 'swe'],
    hours: 28,
    pitch: 'An eval harness for an LLM feature: golden dataset, LLM-as-judge scoring, and a CI gate that fails the build when quality regresses.',
    proves: [
      'Designing eval datasets',
      'LLM-as-judge with calibrated rubrics',
      'Regression detection in CI',
      'Treating prompts like tested code',
    ],
    stack: ['Python or Node', 'Anthropic API', 'GitHub Actions', 'Ragas'],
    milestones: [
      'Pick a target feature (e.g. the extractor or RAG app) and collect 60 graded examples',
      'Write a judge prompt with an explicit rubric; spot-check it against human grades',
      'Build the runner: execute the feature over the dataset, score, emit a JSON report',
      'Wire it into GitHub Actions: fail the PR when the score drops below baseline',
      'Add per-category breakdowns so a failure points at what regressed',
      'Deliberately break a prompt and show the gate catching it',
    ],
    stretch: 'Track judge-human agreement over time and re-calibrate the rubric when it drifts.',
    res: [
      { t: 'Your AI product needs evals', u: 'https://hamel.dev/blog/posts/evals/' },
      { t: 'Ragas docs', u: 'https://docs.ragas.io/' },
    ],
  },
  {
    id: 'flagship-agentic-app',
    name: 'Casefile',
    tier: 'flagship',
    tracks: ['swe', 'prod'],
    hours: 90,
    pitch: 'A production agentic app end to end: an assistant over a real domain corpus with RAG, tool-using agents, an eval suite, input and output guardrails, full tracing, and a public deploy.',
    proves: [
      'Combining RAG, agents, and tools in one system',
      'Guardrails against prompt injection and bad output',
      'Eval-gated releases',
      'Observability and cost tracking in production',
      'Shipping and operating a deployed AI system',
    ],
    stack: ['Next.js', 'Postgres', 'pgvector', 'Anthropic API', 'Langfuse', 'Vercel'],
    milestones: [
      'Pick a domain (e.g. contracts, support docs, legislation) and build the RAG core with citations',
      'Add an agent layer with three tools: retrieval, a domain calculator or API, and a report writer',
      'Add guardrails: input classification, output checks, and injection tests from the OWASP LLM Top 10',
      'Instrument everything with Langfuse: traces, token costs, latency per step',
      'Stand up the eval suite from day one and gate deploys on it',
      'Use prompt caching for the static system context and measure the cost drop',
      'Deploy on Vercel with auth, rate limits, and a public demo mode',
    ],
    stretch: 'Add a feedback loop: thumbs-down responses become new eval cases automatically.',
    res: [
      { t: 'OWASP LLM Top 10', u: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/' },
      { t: 'Langfuse docs', u: 'https://langfuse.com/docs' },
      { t: 'Prompt caching', u: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching' },
    ],
  },

  // ---------- System design / HLD ----------
  {
    id: 'url-shortener-hld',
    name: 'Shrinklink',
    tier: 'core',
    tracks: ['hld'],
    hours: 25,
    pitch: 'A URL shortener you actually deploy and load test, shipped with a written design doc defending every choice: key generation, storage, caching, redirects.',
    proves: [
      'Capacity estimation backed by a real load test',
      'Key generation trade-offs',
      'Cache-aside reads at the hot path',
      'Writing a defensible design doc',
    ],
    stack: ['Node.js or Go', 'Postgres', 'Redis', 'k6 or wrk', 'Docker'],
    milestones: [
      'Write the design doc first: requirements, estimates, API, schema, key scheme',
      'Build create and redirect endpoints with base62 keys over Postgres',
      'Add Redis cache-aside on redirects and measure the hit-rate change',
      'Load test to find the breaking point; record p50, p99, and error rates',
      'Fix the top bottleneck found and re-run the load test',
      'Update the doc with measured numbers vs the original estimates',
    ],
    stretch: 'Add click analytics via an async write path so redirects stay fast.',
    res: [
      { t: 'System Design Primer', u: 'https://github.com/donnemartin/system-design-primer' },
    ],
  },
  {
    id: 'order-pipeline-outbox',
    name: 'Orderflow',
    tier: 'flagship',
    tracks: ['hld'],
    hours: 50,
    pitch: 'An event-driven order pipeline where services communicate through a queue, every consumer is idempotent, and the outbox pattern guarantees no event is lost between the database and the broker.',
    proves: [
      'Event-driven service design',
      'Transactional outbox pattern',
      'Idempotent consumers and dedup keys',
      'Reasoning about at-least-once delivery',
    ],
    stack: ['Kafka', 'Postgres', 'Node.js or Java', 'Docker Compose'],
    milestones: [
      'Model the flow: order service, payment service, notification service, one topic each',
      'Ship the naive version: write to DB then publish, and demonstrate the lost-event failure',
      'Add the outbox table plus a relay process; kill it mid-run and show nothing is lost',
      'Make consumers idempotent with processed-event keys; replay a topic to prove it',
      'Add a dead-letter topic and a retry policy for poison messages',
      'Write a runbook: how to replay, how to inspect lag, what each failure looks like',
    ],
    stretch: 'Add a saga: payment failure triggers compensating order cancellation.',
    res: [
      { t: 'Transactional outbox', u: 'https://microservices.io/patterns/data/transactional-outbox.html' },
      { t: 'Kafka documentation', u: 'https://kafka.apache.org/documentation/' },
    ],
  },
  {
    id: 'observability-ministack',
    name: 'Glasshouse',
    tier: 'core',
    tracks: ['hld'],
    hours: 22,
    pitch: 'Instrument a real app with OpenTelemetry, ship metrics and traces to a local stack, build dashboards for the four golden signals, and wire alerts that fire on real failures.',
    proves: [
      'Instrumenting code with OpenTelemetry',
      'Golden signals: latency, traffic, errors, saturation',
      'Dashboard design that answers questions',
      'Alerting on symptoms, not causes',
    ],
    stack: ['OpenTelemetry', 'Prometheus', 'Grafana', 'Docker Compose'],
    milestones: [
      'Pick an app you already built and add OTel traces and metrics to every endpoint',
      'Run Prometheus and Grafana locally via Docker Compose and confirm data flows',
      'Build one dashboard covering the four golden signals for the app',
      'Define alert rules: error-rate spike and p99 latency breach',
      'Inject failures (kill the DB, add latency) and verify alerts fire and traces explain why',
    ],
    stretch: 'Add exemplars so a spike on the dashboard links straight to a slow trace.',
    res: [
      { t: 'OpenTelemetry docs', u: 'https://opentelemetry.io/docs/' },
      { t: 'Google SRE book', u: 'https://sre.google/sre-book/table-of-contents/' },
    ],
  },

  // ---------- LLD ----------
  {
    id: 'parking-lot-lld',
    name: 'LotKeeper',
    tier: 'starter',
    tracks: ['lld'],
    hours: 12,
    pitch: 'The classic Parking Lot machine-coding problem done properly: clean class design, strategy-based pricing, and a test suite that documents the behavior.',
    proves: [
      'Object modeling from requirements',
      'Strategy and factory patterns in context',
      'SOLID boundaries between classes',
      'Test-first machine coding',
    ],
    stack: ['Java or TypeScript', 'JUnit or Vitest'],
    milestones: [
      'Write the requirements list: vehicle types, spot types, multiple floors, pricing',
      'Model the core classes and enums; review the design before writing logic',
      'Implement park and unpark with nearest-spot allocation, tests first',
      'Add pricing as a strategy: hourly, flat, and lost-ticket cases',
      'Handle edge cases: full lot, duplicate entry, invalid ticket',
    ],
    stretch: 'Add a display board showing free spots per floor, updated on every event.',
    res: [
      { t: 'Awesome low-level design', u: 'https://github.com/ashishps1/awesome-low-level-design' },
      { t: 'Design patterns', u: 'https://refactoring.guru/design-patterns' },
    ],
  },
  {
    id: 'splitwise-engine',
    name: 'Settleup',
    tier: 'core',
    tracks: ['lld'],
    hours: 18,
    pitch: 'A Splitwise-style expense engine: groups, equal and exact and percentage splits, running balances, and a debt-simplification step that minimizes settle-up transactions.',
    proves: [
      'Domain modeling for money',
      'Split strategies without float bugs',
      'Balance graph simplification',
      'Designing a clean service API',
    ],
    stack: ['Java or TypeScript', 'JUnit or Vitest'],
    milestones: [
      'Model users, groups, expenses, and splits; store money as integer minor units',
      'Implement equal, exact, and percentage splits with validation, tests first',
      'Maintain pairwise balances and a per-user net balance view',
      'Implement debt simplification and prove total owed is preserved',
      'Expose the engine behind a small service interface with a demo script',
    ],
    stretch: 'Add multi-currency expenses with a pluggable exchange-rate provider.',
    res: [
      { t: 'Awesome low-level design', u: 'https://github.com/ashishps1/awesome-low-level-design' },
    ],
  },
  {
    id: 'concurrent-cache-lib',
    name: 'Cachet',
    tier: 'core',
    tracks: ['lld'],
    hours: 20,
    pitch: 'A thread-safe LRU cache library with TTL support: correct under concurrent access, benchmarked, and published with a clean API like a real library.',
    proves: [
      'Hashmap plus doubly linked list internals',
      'Thread safety and lock granularity',
      'API design for a reusable library',
      'Benchmarking under contention',
    ],
    stack: ['Java or Go', 'JUnit or go test', 'JMH or pprof'],
    milestones: [
      'Implement single-threaded LRU with O(1) get and put, fully tested',
      'Add TTL expiry with lazy eviction on read',
      'Make it thread safe; write a stress test with many readers and writers',
      'Benchmark coarse locking vs finer-grained locking and record the numbers',
      'Package it with docs, examples, and eviction-callback hooks',
    ],
    stretch: 'Add a segmented (sharded) mode and show the throughput gain under contention.',
    res: [
      { t: 'LRU Cache problem', u: 'https://leetcode.com/problems/lru-cache/' },
      { t: 'Java concurrency tutorial', u: 'https://jenkov.com/tutorials/java-concurrency/index.html' },
    ],
  },

  // ---------- DSA ----------
  {
    id: 'dsa-from-scratch',
    name: 'Bare Structures',
    tier: 'core',
    tracks: ['dsa'],
    hours: 35,
    pitch: 'A data-structures library written from scratch: linked list, stack, queue, heap, trie, and graph with BFS/DFS/Dijkstra, every structure tested and complexity-documented.',
    proves: [
      'Implementing structures, not just using them',
      'Complexity analysis you can defend',
      'Edge-case driven testing',
      'Clean generic APIs',
    ],
    stack: ['TypeScript or Python', 'Vitest or pytest'],
    milestones: [
      'Linked list, stack, and queue with full test coverage and documented big-O',
      'Binary heap with heapify, plus a priority queue built on it',
      'Trie with insert, search, prefix search, and delete',
      'Graph with adjacency list, BFS, DFS, and cycle detection',
      'Dijkstra and topological sort on the graph type',
      'README table: every operation, its complexity, and the test that proves it',
    ],
    stretch: 'Add a union-find structure and use it for Kruskal minimum spanning tree.',
    res: [
      { t: 'Graph algorithms', u: 'https://cp-algorithms.com/graph/' },
      { t: 'NeetCode practice', u: 'https://neetcode.io/practice' },
    ],
  },
  {
    id: 'spaced-rep-tracker',
    name: 'Recall150',
    tier: 'starter',
    tracks: ['dsa'],
    hours: 15,
    pitch: 'A spaced-repetition tracker for NeetCode 150: log each attempt, and the app schedules reviews so problems you struggled with come back sooner.',
    proves: [
      'Implementing a spaced-repetition algorithm',
      'CRUD app with real persistence',
      'Progress visualization by topic',
      'Building a tool you use daily',
    ],
    stack: ['Next.js', 'SQLite or Postgres', 'Tailwind', 'Vercel'],
    milestones: [
      'Seed the NeetCode 150 list with topic tags into the database',
      'Log attempts: solved clean, solved with hints, or failed, plus time taken',
      'Implement the review scheduler: intervals shrink on failure, grow on clean solves',
      'Build the daily queue view: what to re-attempt today and why',
      'Add a topic heatmap of strong and weak areas, then deploy',
    ],
    stretch: 'Export a weekly review summary and streak stats as a shareable page.',
    res: [
      { t: 'NeetCode practice', u: 'https://neetcode.io/practice' },
      { t: 'Vercel', u: 'https://vercel.com/' },
    ],
  },
];
