import type { Track } from './types';

// DSA track — mirrors the NeetCode roadmap structure and topic order.

export const dsa: Track = {
  id: 'dsa',
  name: 'Data Structures & Algorithms',
  emoji: '🧠',
  blurb: 'The NeetCode-style path from Arrays & Hashing to Dynamic Programming and Graphs. Pattern-first, interview-ready.',
  nodes: [
    { id: 'arrays', t: 'Arrays & Hashing', x: 800, y: 90, lv: 'F', h: 20,
      s: 'The foundation: arrays, hash maps, and hash sets. Master these before anything else.',
      learn: ['Array traversal + prefix sums', 'Hash maps / sets for O(1) lookup', 'Frequency counting', 'Duplicates, grouping, encoding'],
      tools: ['Hash map', 'Hash set'],
      proj: 'Solve Two Sum, Group Anagrams, Top K Frequent, Product of Array.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: array tag', u: 'https://leetcode.com/tag/array/' }, { t: 'Striver A2Z DSA', u: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/' }],
      deps: [] },
    { id: 'twoP', t: 'Two Pointers', x: 650, y: 245, lv: 'F', h: 12,
      s: 'Two indices moving through a structure — sorted arrays, palindromes, pair sums.',
      learn: ['Opposite-end pointers', 'Fast/slow pointers', 'Sorted-array techniques', 'In-place partitioning'],
      tools: ['Two pointers'],
      proj: 'Valid Palindrome, Two Sum II, 3Sum, Container With Most Water.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: two-pointers', u: 'https://leetcode.com/tag/two-pointers/' }],
      deps: ['arrays'] },
    { id: 'stack', t: 'Stack', x: 980, y: 245, lv: 'F', h: 12,
      s: 'LIFO structure — parsing, monotonic stacks, and matching problems.',
      learn: ['Valid parentheses / matching', 'Monotonic stack', 'Min stack', 'Expression evaluation'],
      tools: ['Stack'],
      proj: 'Valid Parentheses, Min Stack, Daily Temperatures, Car Fleet.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: stack tag', u: 'https://leetcode.com/tag/stack/' }],
      deps: ['arrays'] },
    { id: 'binary', t: 'Binary Search', x: 470, y: 400, lv: 'C', h: 14,
      s: 'Halve the search space each step — on arrays and on answers.',
      learn: ['Classic binary search + bounds', 'Search rotated / 2D arrays', 'Binary search on the answer', 'Off-by-one discipline'],
      tools: ['Binary search'],
      proj: 'Binary Search, Search a 2D Matrix, Koko Eating Bananas, Min in Rotated.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: binary-search', u: 'https://leetcode.com/tag/binary-search/' }],
      deps: ['twoP'] },
    { id: 'sliding', t: 'Sliding Window', x: 720, y: 400, lv: 'C', h: 14,
      s: 'A moving window over a sequence — substrings and subarrays in O(n).',
      learn: ['Fixed vs variable window', 'Window state (hash/counts)', 'Shrink/grow conditions', 'Best/longest/shortest patterns'],
      tools: ['Sliding window'],
      proj: 'Best Time to Buy/Sell, Longest Substring w/o Repeat, Min Window Substring.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: sliding-window', u: 'https://leetcode.com/tag/sliding-window/' }],
      deps: ['twoP'] },
    { id: 'linked', t: 'Linked List', x: 970, y: 400, lv: 'C', h: 14,
      s: 'Pointer manipulation, cycle detection, and merging.',
      learn: ['Reverse a list', 'Fast/slow (cycle, middle)', 'Merge + reorder', 'Dummy-node technique'],
      tools: ['Linked list'],
      proj: 'Reverse List, Merge Two Lists, Linked List Cycle, LRU Cache.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: linked-list', u: 'https://leetcode.com/tag/linked-list/' }],
      deps: ['twoP'] },
    { id: 'trees', t: 'Trees', x: 760, y: 560, lv: 'C', h: 24,
      s: 'Binary trees + BSTs: traversal, recursion, and the DFS/BFS toolkit.',
      learn: ['DFS (pre/in/post) + BFS', 'BST properties + operations', 'Recursion on trees', 'Depth, diameter, LCA'],
      tools: ['Tree', 'Recursion'],
      proj: 'Invert Tree, Max Depth, Level Order, Validate BST, LCA, Serialize.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: tree tag', u: 'https://leetcode.com/tag/tree/' }],
      deps: ['binary', 'sliding', 'linked', 'stack'] },
    { id: 'tries', t: 'Tries', x: 560, y: 715, lv: 'C', h: 10,
      s: 'Prefix trees for fast word lookup and autocomplete.',
      learn: ['Trie insert / search / prefix', 'Word dictionaries', 'Design problems', 'DFS on a trie'],
      tools: ['Trie'],
      proj: 'Implement Trie, Add & Search Word, Word Search II.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: trie tag', u: 'https://leetcode.com/tag/trie/' }],
      deps: ['trees'] },
    { id: 'back', t: 'Backtracking', x: 960, y: 715, lv: 'A', h: 16,
      s: 'Explore all possibilities with pruning — subsets, permutations, combinations.',
      learn: ['Decision tree + backtrack', 'Subsets / permutations / combinations', 'Pruning + constraints', 'Grid backtracking'],
      tools: ['Recursion', 'Backtracking'],
      proj: 'Subsets, Combination Sum, Permutations, Word Search, N-Queens.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: backtracking', u: 'https://leetcode.com/tag/backtracking/' }],
      deps: ['trees'] },
    { id: 'heap', t: 'Heap / Priority Queue', x: 760, y: 715, lv: 'C', h: 14,
      s: 'Always-get-the-min/max structure — top-K, scheduling, streaming medians.',
      learn: ['Min/max heap operations', 'Top-K + k-way merge', 'Heapify', 'Two-heap median'],
      tools: ['Heap', 'Priority queue'],
      proj: 'Kth Largest, Last Stone Weight, K Closest Points, Task Scheduler.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: heap tag', u: 'https://leetcode.com/tag/heap-priority-queue/' }],
      deps: ['trees'] },
    { id: 'intervals', t: 'Intervals', x: 360, y: 875, lv: 'C', h: 10,
      s: 'Merging, inserting, and scheduling overlapping ranges.',
      learn: ['Sort by start/end', 'Merge + insert intervals', 'Overlap detection', 'Meeting rooms'],
      tools: ['Sorting', 'Heap'],
      proj: 'Merge Intervals, Insert Interval, Non-overlapping, Meeting Rooms.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: intervals', u: 'https://leetcode.com/tag/interval/' }],
      deps: ['heap'] },
    { id: 'greedy', t: 'Greedy', x: 560, y: 875, lv: 'A', h: 12,
      s: 'Local optimal choices that lead to a global optimum — when they work.',
      learn: ['Greedy choice + exchange argument', 'Interval scheduling', 'Jump games', 'When greedy fails'],
      tools: ['Greedy'],
      proj: 'Maximum Subarray, Jump Game, Gas Station, Hand of Straights.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: greedy tag', u: 'https://leetcode.com/tag/greedy/' }],
      deps: ['heap'] },
    { id: 'graphs', t: 'Graphs', x: 900, y: 875, lv: 'A', h: 20,
      s: 'BFS/DFS, connected components, topological sort — the core graph toolkit.',
      learn: ['Adjacency list/matrix', 'BFS + DFS traversal', 'Islands / grid graphs', 'Topological sort + cycle detection'],
      tools: ['Graph', 'BFS', 'DFS'],
      proj: 'Number of Islands, Clone Graph, Course Schedule, Pacific Atlantic.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'WilliamFiset: Graph Theory', u: 'https://www.youtube.com/playlist?list=PLDV1Zeh2NRsDGO4--qE8yH72HFL1Km93P' }],
      deps: ['back'] },
    { id: 'oneDP', t: '1-D Dynamic Programming', x: 1120, y: 875, lv: 'A', h: 20,
      s: 'Overlapping subproblems in one dimension — memoization and tabulation.',
      learn: ['Recurrence + memoization', 'Bottom-up tabulation', 'House robber / climbing stairs', 'Subsequence + partition DP'],
      tools: ['DP'],
      proj: 'Climbing Stairs, House Robber, Coin Change, Longest Inc. Subsequence.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'Striver: DP playlist', u: 'https://takeuforward.org/dynamic-programming/strivers-dp-series-dynamic-programming-problems/' }],
      deps: ['back'] },
    { id: 'advG', t: 'Advanced Graphs', x: 780, y: 1035, lv: 'A', h: 18,
      s: "Weighted graphs and shortest paths: Dijkstra, Prim, Kruskal, Bellman-Ford.",
      learn: ["Dijkstra + Bellman-Ford", 'MST (Prim / Kruskal + union-find)', 'Union-Find (DSU)', 'Min-cost / network problems'],
      tools: ['Dijkstra', 'Union-Find'],
      proj: 'Network Delay Time, Min Cost to Connect Points, Swim in Water.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'CP-Algorithms: graphs', u: 'https://cp-algorithms.com/graph/' }],
      deps: ['heap', 'graphs'] },
    { id: 'twoDP', t: '2-D Dynamic Programming', x: 1010, y: 1035, lv: 'A', h: 20,
      s: 'DP over a grid or two sequences — the hardest DP tier.',
      learn: ['Grid DP', 'Two-sequence DP (LCS, edit distance)', 'Knapsack variants', 'State compression'],
      tools: ['DP'],
      proj: 'Unique Paths, Longest Common Subseq, Edit Distance, 0/1 Knapsack.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'Striver: DP playlist', u: 'https://takeuforward.org/dynamic-programming/strivers-dp-series-dynamic-programming-problems/' }],
      deps: ['graphs', 'oneDP'] },
    { id: 'bit', t: 'Bit Manipulation', x: 1220, y: 1035, lv: 'C', h: 10,
      s: 'Work directly with bits — XOR tricks, masks, and counting.',
      learn: ['AND/OR/XOR/shift', 'Counting bits, single number', 'Bitmask subsets', 'Overflow-safe tricks'],
      tools: ['Bitwise ops'],
      proj: 'Single Number, Number of 1 Bits, Counting Bits, Reverse Bits.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: bit-manipulation', u: 'https://leetcode.com/tag/bit-manipulation/' }],
      deps: ['oneDP'] },
    { id: 'math', t: 'Math & Geometry', x: 1000, y: 1190, lv: 'C', h: 12,
      s: 'Matrix ops, number theory, and geometry problems.',
      learn: ['Matrix rotation / spiral', 'GCD / primes / modular math', 'Coordinate geometry', 'Overflow handling'],
      tools: ['Math'],
      proj: 'Rotate Image, Spiral Matrix, Set Matrix Zeroes, Happy Number.',
      res: [{ t: 'NeetCode: practice', u: 'https://neetcode.io/practice' }, { t: 'LeetCode: math tag', u: 'https://leetcode.com/tag/math/' }],
      deps: ['advG', 'twoDP', 'bit'] },
  ],
};
