import type { Track } from './types';

// System design tracks: High-Level Design (HLD) and Low-Level Design (LLD / OOD).

export const hld: Track = {
  id: 'hld',
  name: 'High-Level Design (System Design)',
  emoji: '🏛️',
  blurb: 'Design large-scale distributed systems: databases, caching, queues, sharding, consistency, and real case studies.',
  nodes: [
    { id: 'fund', t: 'Fundamentals & Estimation', x: 800, y: 90, lv: 'F', h: 12,
      s: 'The vocabulary of scale: latency vs throughput, availability, and back-of-the-envelope math.',
      learn: ['Client–server, request lifecycle', 'Latency, throughput, availability, SLA', 'Vertical vs horizontal scaling', 'Back-of-envelope estimation (QPS, storage, bandwidth)'],
      tools: ['Napkin math', 'Latency numbers'],
      proj: 'Estimate QPS + storage for a photo-sharing app at 10M DAU.',
      res: [{ t: 'System Design Primer', u: 'https://github.com/donnemartin/system-design-primer' }, { t: 'Hello Interview: SD in a hurry', u: 'https://www.hellointerview.com/learn/system-design/in-a-hurry/introduction' }, { t: 'Latency numbers every dev should know', u: 'https://gist.github.com/jboner/2841832' }],
      deps: [] },
    { id: 'net', t: 'Networking & Protocols', x: 585, y: 245, lv: 'F', h: 14,
      s: 'How bytes actually move: DNS, HTTP, TCP/UDP, TLS, and long-lived connections.',
      learn: ['DNS, IP, TCP vs UDP', 'HTTP/1.1, HTTP/2, HTTP/3, HTTPS/TLS', 'WebSockets, SSE, long polling', 'CDNs + edge basics'],
      tools: ['HTTP', 'TLS', 'WebSockets'],
      proj: 'Diagram what happens end-to-end when you load a web page.',
      res: [{ t: 'Cloudflare: Learning Center', u: 'https://www.cloudflare.com/learning/' }, { t: 'ByteByteGo (YouTube)', u: 'https://www.youtube.com/@ByteByteGo' }],
      deps: ['fund'] },
    { id: 'api', t: 'APIs & Communication', x: 1015, y: 245, lv: 'C', h: 12,
      s: 'How services talk: REST, gRPC, GraphQL, and choosing between them.',
      learn: ['REST design + versioning', 'gRPC + protobufs', 'GraphQL tradeoffs', 'Idempotency + pagination'],
      tools: ['REST', 'gRPC', 'GraphQL'],
      proj: 'Design a REST API for a URL shortener with versioning + rate limits.',
      res: [{ t: 'ByteByteGo: API styles', u: 'https://blog.bytebytego.com/p/api-architecture-styles' }, { t: 'gRPC docs', u: 'https://grpc.io/docs/' }],
      deps: ['fund'] },
    { id: 'db', t: 'Databases: SQL vs NoSQL', x: 800, y: 400, lv: 'C', h: 16,
      s: 'Pick the right store: relational, document, key-value, wide-column, and why.',
      learn: ['ACID vs BASE', 'SQL vs document/KV/wide-column/graph', 'When to use each', 'Transactions + isolation levels'],
      tools: ['PostgreSQL', 'MongoDB', 'Cassandra', 'Redis'],
      proj: 'Choose + justify a datastore for a chat app and a ledger.',
      res: [{ t: 'DDIA (book site)', u: 'https://dataintensive.net/' }, { t: 'ByteByteGo: SQL vs NoSQL', u: 'https://blog.bytebytego.com/p/sql-vs-nosql-7-simple-questions' }],
      deps: ['net', 'api'] },
    { id: 'model', t: 'Data Modeling & Indexing', x: 585, y: 555, lv: 'C', h: 14,
      s: 'Schema and index design that survives scale and access-pattern change.',
      learn: ['Normalization vs denormalization', 'Indexes (B-tree, hash, inverted)', 'Access-pattern-first modeling', 'Hot keys + write amplification'],
      tools: ['SQL', 'DynamoDB single-table'],
      proj: 'Model + index a schema for a news feed by access pattern.',
      res: [{ t: 'Use The Index, Luke', u: 'https://use-the-index-luke.com/' }, { t: 'DynamoDB modeling (Alex DeBrie)', u: 'https://www.alexdebrie.com/posts/dynamodb-single-table/' }],
      deps: ['db'] },
    { id: 'cache', t: 'Caching', x: 1015, y: 555, lv: 'C', h: 14,
      s: 'The fastest query is the one you never make. Cache layers, strategies, and pitfalls.',
      learn: ['Cache-aside, write-through, write-back', 'Eviction (LRU/LFU/TTL)', 'CDN + browser + app + DB caches', 'Cache invalidation + stampede'],
      tools: ['Redis', 'Memcached', 'CDN'],
      proj: 'Add a cache layer to your feed design; handle invalidation.',
      res: [{ t: 'Redis: caching patterns', u: 'https://redis.io/docs/latest/develop/use/patterns/' }, { t: 'System Design Primer: caching', u: 'https://github.com/donnemartin/system-design-primer#cache' }],
      deps: ['db'] },
    { id: 'lb', t: 'Load Balancing', x: 585, y: 710, lv: 'C', h: 12,
      s: 'Spread traffic across instances and survive failures.',
      learn: ['L4 vs L7 load balancing', 'Algorithms (round-robin, least-conn, hashing)', 'Health checks + failover', 'Sticky sessions'],
      tools: ['NGINX', 'HAProxy', 'ELB'],
      proj: 'Add load balancing + health checks to your architecture diagram.',
      res: [{ t: 'System Design Primer: LB', u: 'https://github.com/donnemartin/system-design-primer#load-balancer' }, { t: 'NGINX: load balancing', u: 'https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/' }],
      deps: ['model'] },
    { id: 'repl', t: 'Replication & Consistency', x: 1015, y: 710, lv: 'A', h: 18,
      s: 'Copies for availability, and the hard truth of CAP.',
      learn: ['Leader–follower + multi-leader replication', 'Sync vs async replication', 'CAP, PACELC, consistency models', 'Read/write quorums'],
      tools: ['Postgres replication', 'Raft'],
      proj: 'Reason through availability vs consistency for a payments system.',
      res: [{ t: 'DDIA: replication (ch.5)', u: 'https://dataintensive.net/' }, { t: 'CAP theorem explained', u: 'https://www.bytebytego.com/' }],
      deps: ['cache'] },
    { id: 'shard', t: 'Partitioning / Sharding', x: 800, y: 865, lv: 'A', h: 16,
      s: 'Split data across nodes without creating hot spots.',
      learn: ['Range vs hash partitioning', 'Consistent hashing', 'Rebalancing + hotspots', 'Cross-shard queries'],
      tools: ['Consistent hashing', 'Vitess'],
      proj: 'Shard your feed DB with consistent hashing; handle a hot celebrity.',
      res: [{ t: 'Consistent hashing (ByteByteGo)', u: 'https://blog.bytebytego.com/p/consistent-hashing' }, { t: 'DDIA: partitioning (ch.6)', u: 'https://dataintensive.net/' }],
      deps: ['lb', 'repl'] },
    { id: 'queue', t: 'Message Queues & Async', x: 585, y: 1020, lv: 'A', h: 16,
      s: 'Decouple with async: queues, streams, and event-driven architecture.',
      learn: ['Queues vs pub/sub vs log (Kafka)', 'At-least/at-most/exactly-once', 'Backpressure + dead-letter queues', 'Event-driven design'],
      tools: ['Kafka', 'RabbitMQ', 'SQS'],
      proj: 'Redesign a synchronous flow (e.g. order → email) as event-driven.',
      res: [{ t: 'Apache Kafka docs', u: 'https://kafka.apache.org/documentation/' }, { t: 'Confluent: Kafka 101', u: 'https://developer.confluent.io/courses/apache-kafka/events/' }],
      deps: ['shard'] },
    { id: 'rate', t: 'Rate Limiting & Throttling', x: 1015, y: 1020, lv: 'C', h: 10,
      s: 'Protect services from abuse and overload.',
      learn: ['Token bucket, leaky bucket, sliding window', 'Distributed rate limiting (Redis)', 'Per-user vs global limits', '429s + retry-after'],
      tools: ['Redis', 'API gateway'],
      proj: 'Design a distributed rate limiter for an API gateway.',
      res: [{ t: 'System Design: rate limiter (ByteByteGo)', u: 'https://blog.bytebytego.com/p/rate-limiting-fundamentals' }, { t: 'Cloudflare: rate limiting', u: 'https://developers.cloudflare.com/waf/rate-limiting-rules/' }],
      deps: ['shard'] },
    { id: 'search', t: 'Search Systems', x: 585, y: 1175, lv: 'A', h: 14,
      s: 'Full-text search and ranking at scale.',
      learn: ['Inverted indexes', 'Elasticsearch/OpenSearch basics', 'Relevance + ranking', 'Autocomplete/typeahead'],
      tools: ['Elasticsearch', 'OpenSearch'],
      proj: 'Design search + typeahead for a product catalog.',
      res: [{ t: 'Elasticsearch: guide', u: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html' }, { t: 'Designing a search system', u: 'https://github.com/donnemartin/system-design-primer' }],
      deps: ['queue'] },
    { id: 'blob', t: 'Object Storage & CDN', x: 1015, y: 1175, lv: 'C', h: 10,
      s: 'Store and deliver large files and media globally.',
      learn: ['Object storage (S3) vs block/file', 'CDN caching + edge', 'Presigned URLs, chunked uploads', 'Media pipelines'],
      tools: ['S3', 'CloudFront', 'Cloudflare'],
      proj: 'Design image upload + delivery with an S3 + CDN pipeline.',
      res: [{ t: 'AWS S3 docs', u: 'https://docs.aws.amazon.com/s3/' }, { t: 'Cloudflare: CDN', u: 'https://www.cloudflare.com/learning/cdn/what-is-a-cdn/' }],
      deps: ['rate'] },
    { id: 'micro', t: 'Microservices & Architecture', x: 800, y: 1330, lv: 'A', h: 16,
      s: 'Monolith vs microservices, gateways, and service boundaries.',
      learn: ['Monolith vs microservices tradeoffs', 'API gateway + service discovery', 'Service boundaries (DDD)', 'Inter-service communication'],
      tools: ['API gateway', 'Kubernetes'],
      proj: 'Split a monolith into services and draw the gateway + discovery.',
      res: [{ t: 'microservices.io (Chris Richardson)', u: 'https://microservices.io/patterns/' }, { t: 'Martin Fowler: Microservices', u: 'https://martinfowler.com/articles/microservices.html' }],
      deps: ['search', 'blob'] },
    { id: 'dist', t: 'Distributed Transactions & Consistency Patterns', x: 585, y: 1485, lv: 'A', h: 14,
      s: 'Keep data correct across services without a global lock.',
      learn: ['2PC vs Saga pattern', 'Idempotency keys', 'Outbox + CDC', 'Eventual consistency in practice'],
      tools: ['Saga', 'Debezium (CDC)'],
      proj: 'Design an order+payment flow with a saga + idempotency.',
      res: [{ t: 'Saga pattern (microservices.io)', u: 'https://microservices.io/patterns/data/saga.html' }, { t: 'Transactional outbox', u: 'https://microservices.io/patterns/data/transactional-outbox.html' }],
      deps: ['micro'] },
    { id: 'obs', t: 'Observability & Reliability', x: 1015, y: 1485, lv: 'A', h: 12,
      s: 'Know when it breaks and why: metrics, logs, traces, SLOs.',
      learn: ['SLI/SLO/SLA + error budgets', 'Metrics, logs, distributed tracing', 'Health checks + circuit breakers', 'Graceful degradation'],
      tools: ['Prometheus', 'Grafana', 'OpenTelemetry'],
      proj: 'Define SLOs + a monitoring plan for your microservice design.',
      res: [{ t: 'Google SRE Book', u: 'https://sre.google/sre-book/table-of-contents/' }, { t: 'OpenTelemetry docs', u: 'https://opentelemetry.io/docs/' }],
      deps: ['micro'] },
    { id: 'sec', t: 'Security & Auth', x: 585, y: 1640, lv: 'C', h: 12,
      s: 'AuthN/AuthZ, encryption, and protecting data in transit and at rest.',
      learn: ['OAuth2 + OpenID Connect, JWT', 'Sessions vs tokens', 'Encryption at rest/in transit', 'Common attacks (OWASP)'],
      tools: ['OAuth2', 'JWT', 'TLS'],
      proj: 'Design auth for a multi-tenant SaaS with OAuth2 + JWT.',
      res: [{ t: 'OAuth 2.0 Simplified', u: 'https://www.oauth.com/' }, { t: 'OWASP Top 10', u: 'https://owasp.org/www-project-top-ten/' }],
      deps: ['dist'] },
    { id: 'scale', t: 'Scalability & Design Patterns', x: 1015, y: 1640, lv: 'A', h: 14,
      s: 'The reusable moves: CQRS, event sourcing, fan-out, and more.',
      learn: ['CQRS + event sourcing', 'Fan-out on write vs read (feeds)', 'Bloom filters, geohashing', 'Multi-region + disaster recovery'],
      tools: ['CQRS', 'Event sourcing'],
      proj: 'Choose fan-out strategy for a Twitter-like feed and justify it.',
      res: [{ t: 'System Design Primer', u: 'https://github.com/donnemartin/system-design-primer' }, { t: 'High Scalability blog', u: 'http://highscalability.com/' }],
      deps: ['obs'] },
    { id: 'cases', t: 'Case Studies & Mock Interviews', x: 800, y: 1795, lv: 'A', h: 20,
      s: 'Put it together: design real systems under interview conditions.',
      learn: ['A repeatable framework (requirements → API → data → scale)', 'Design: TinyURL, Twitter, WhatsApp, Uber, Netflix', 'Tradeoff articulation', 'Timeboxed mock interviews'],
      tools: ['Whiteboard', 'excalidraw'],
      proj: 'Do 5 full designs end-to-end and record your tradeoffs.',
      res: [{ t: 'Hello Interview: guided problems', u: 'https://www.hellointerview.com/learn/system-design' }, { t: 'ByteByteGo (YouTube)', u: 'https://www.youtube.com/@ByteByteGo' }, { t: 'Gaurav Sen (YouTube)', u: 'https://www.youtube.com/@gkcs' }],
      deps: ['sec', 'scale'] },
  ],
};

export const lld: Track = {
  id: 'lld',
  name: 'Low-Level Design (OOD)',
  emoji: '🧩',
  blurb: 'Object-oriented design done right: SOLID, design patterns, concurrency, and the classic machine-coding problems.',
  nodes: [
    { id: 'oop', t: 'OOP Fundamentals', x: 800, y: 90, lv: 'F', h: 12,
      s: 'The four pillars, done properly — not just syntax.',
      learn: ['Encapsulation, abstraction, inheritance, polymorphism', 'Classes, objects, interfaces', 'Composition vs inheritance', 'Access modifiers + invariants'],
      tools: ['Java / C++ / Python'],
      proj: 'Model a deck of cards with clean classes + interfaces.',
      res: [{ t: 'Refactoring Guru: OOP', u: 'https://refactoring.guru/design-patterns/what-is-pattern' }, { t: 'ArjanCodes (YouTube)', u: 'https://www.youtube.com/@ArjanCodes' }],
      deps: [] },
    { id: 'uml', t: 'UML & Class Diagrams', x: 585, y: 245, lv: 'F', h: 8,
      s: 'Communicate a design visually before you write code.',
      learn: ['Class, sequence, use-case diagrams', 'Associations, aggregation, composition', 'Multiplicity + relationships', 'Reading + drawing UML fast'],
      tools: ['draw.io', 'PlantUML', 'Mermaid'],
      proj: 'Draw a class + sequence diagram for an ATM withdrawal.',
      res: [{ t: 'PlantUML: class diagram', u: 'https://plantuml.com/class-diagram' }, { t: 'UML basics (Visual Paradigm)', u: 'https://www.visual-paradigm.com/guide/uml-unified-modeling-language/uml-class-diagram-tutorial/' }],
      deps: ['oop'] },
    { id: 'solid', t: 'SOLID Principles', x: 1015, y: 245, lv: 'C', h: 12,
      s: 'The five principles that keep OO code flexible and testable.',
      learn: ['Single Responsibility, Open/Closed', 'Liskov Substitution', 'Interface Segregation', 'Dependency Inversion'],
      tools: ['Any OO language'],
      proj: 'Refactor a "god class" to satisfy all five SOLID principles.',
      res: [{ t: 'SOLID explained (Baeldung)', u: 'https://www.baeldung.com/solid-principles' }, { t: 'awesome-low-level-design', u: 'https://github.com/ashishps1/awesome-low-level-design' }],
      deps: ['oop'] },
    { id: 'princ', t: 'Design Principles', x: 800, y: 400, lv: 'C', h: 10,
      s: 'Beyond SOLID: DRY, KISS, YAGNI, and low coupling / high cohesion.',
      learn: ['DRY, KISS, YAGNI', 'Coupling vs cohesion', 'Composition over inheritance', 'Program to interfaces'],
      tools: ['Any OO language'],
      proj: 'Take a tightly coupled module and decouple it via interfaces.',
      res: [{ t: 'Refactoring Guru: design principles', u: 'https://refactoring.guru/design-patterns/design-principles' }, { t: 'awesome-low-level-design', u: 'https://github.com/ashishps1/awesome-low-level-design' }],
      deps: ['uml', 'solid'] },
    { id: 'creat', t: 'Creational Patterns', x: 585, y: 555, lv: 'C', h: 12,
      s: 'How objects get made: Factory, Builder, Singleton, and friends.',
      learn: ['Factory + Abstract Factory', 'Builder', 'Singleton (and its traps)', 'Prototype'],
      tools: ['Any OO language'],
      proj: 'Build a pluggable notification factory (email/SMS/push).',
      res: [{ t: 'Refactoring Guru: creational', u: 'https://refactoring.guru/design-patterns/creational-patterns' }, { t: 'C. Okhravi: patterns playlist', u: 'https://www.youtube.com/playlist?list=PLrhzvIcii6GNjpARdnO4ueTUAVR9eMBpc' }],
      deps: ['princ'] },
    { id: 'struct', t: 'Structural Patterns', x: 1015, y: 555, lv: 'C', h: 12,
      s: 'How objects compose: Adapter, Decorator, Facade, Proxy, Composite.',
      learn: ['Adapter + Bridge', 'Decorator + Composite', 'Facade + Proxy', 'Flyweight'],
      tools: ['Any OO language'],
      proj: 'Add features to a coffee order with the Decorator pattern.',
      res: [{ t: 'Refactoring Guru: structural', u: 'https://refactoring.guru/design-patterns/structural-patterns' }, { t: 'Head First Design Patterns', u: 'https://www.oreilly.com/library/view/head-first-design/9781492077992/' }],
      deps: ['princ'] },
    { id: 'behav', t: 'Behavioral Patterns', x: 800, y: 710, lv: 'C', h: 14,
      s: 'How objects collaborate: Observer, Strategy, State, Command, and more.',
      learn: ['Observer + Mediator', 'Strategy + State', 'Command + Chain of Responsibility', 'Template Method + Iterator'],
      tools: ['Any OO language'],
      proj: 'Model a vending machine with the State pattern.',
      res: [{ t: 'Refactoring Guru: behavioral', u: 'https://refactoring.guru/design-patterns/behavioral-patterns' }, { t: 'awesome-low-level-design', u: 'https://github.com/ashishps1/awesome-low-level-design' }],
      deps: ['creat', 'struct'] },
    { id: 'conc', t: 'Concurrency & Thread-Safety', x: 585, y: 865, lv: 'A', h: 14,
      s: 'Design objects that behave under many threads.',
      learn: ['Threads, locks, synchronization', 'Race conditions + deadlocks', 'Thread-safe singletons + collections', 'Producer–consumer'],
      tools: ['Java concurrency', 'threading'],
      proj: 'Build a thread-safe in-memory cache with expiry.',
      res: [{ t: 'Jenkov: Java Concurrency', u: 'https://jenkov.com/tutorials/java-concurrency/index.html' }, { t: 'awesome-low-level-design', u: 'https://github.com/ashishps1/awesome-low-level-design' }],
      deps: ['behav'] },
    { id: 'clean', t: 'Clean Code & Refactoring', x: 1015, y: 865, lv: 'C', h: 10,
      s: 'Readable, testable code and safe, incremental improvement.',
      learn: ['Naming, functions, comments', 'Code smells', 'Refactoring techniques', 'Boundaries + error handling'],
      tools: ['Any language'],
      proj: 'Refactor a messy 200-line function into clean units.',
      res: [{ t: 'Refactoring Guru: smells + refactorings', u: 'https://refactoring.guru/refactoring' }, { t: 'Clean Code (book)', u: 'https://www.oreilly.com/library/view/clean-code-a/9780136083238/' }],
      deps: ['behav'] },
    { id: 'domain', t: 'Domain Modeling & API Design', x: 800, y: 1020, lv: 'A', h: 12,
      s: 'Turn requirements into entities, relationships, and clean interfaces.',
      learn: ['Requirement → entities + relationships', 'Class + interface design', 'Bounded contexts (DDD-lite)', 'API/interface ergonomics'],
      tools: ['UML', 'DDD'],
      proj: 'Model the domain for a food-delivery app (entities + APIs).',
      res: [{ t: 'DDD reference (Evans)', u: 'https://www.domainlanguage.com/ddd/reference/' }, { t: 'awesome-low-level-design', u: 'https://github.com/ashishps1/awesome-low-level-design' }],
      deps: ['conc', 'clean'] },
    { id: 'test', t: 'Testing & TDD', x: 585, y: 1175, lv: 'C', h: 10,
      s: 'Prove your design works and keep it that way.',
      learn: ['Unit tests + arrange-act-assert', 'Mocks, stubs, fakes', 'Test-driven development loop', 'Testable design (DI)'],
      tools: ['JUnit', 'pytest', 'Jest'],
      proj: 'TDD a small library (e.g. a rate limiter) from tests first.',
      res: [{ t: 'Martin Fowler: Mocks vs Stubs', u: 'https://martinfowler.com/articles/mocksArentStubs.html' }, { t: 'TDD by Example (book)', u: 'https://www.oreilly.com/library/view/test-driven-development/0321146530/' }],
      deps: ['domain'] },
    { id: 'machine', t: 'Machine-Coding Approach', x: 1015, y: 1175, lv: 'A', h: 10,
      s: 'A repeatable method to solve any LLD problem in 60–90 minutes.',
      learn: ['Clarify requirements + scope', 'Identify entities + relationships', 'Apply patterns deliberately', 'Working code + extensibility'],
      tools: ['Your language of choice'],
      proj: 'Solve one timed machine-coding problem end-to-end.',
      res: [{ t: 'awesome-low-level-design: problems', u: 'https://github.com/ashishps1/awesome-low-level-design#lld-problems' }, { t: 'Grokking the LLD Interview', u: 'https://www.educative.io/courses/grokking-the-low-level-design-interview-using-ood-principles' }],
      deps: ['domain'] },
    { id: 'prob1', t: 'Classic LLD Problems', x: 585, y: 1330, lv: 'A', h: 16,
      s: 'The interview staples: Parking Lot, Elevator, BookMyShow, Vending Machine.',
      learn: ['Parking Lot system', 'Elevator / lift system', 'Movie booking (BookMyShow)', 'Vending machine'],
      tools: ['Patterns + SOLID'],
      proj: 'Fully design + code the Parking Lot system.',
      res: [{ t: 'awesome-low-level-design', u: 'https://github.com/ashishps1/awesome-low-level-design' }, { t: 'Refactoring Guru: patterns', u: 'https://refactoring.guru/design-patterns' }],
      deps: ['test', 'machine'] },
    { id: 'prob2', t: 'More LLD Problems', x: 1015, y: 1330, lv: 'A', h: 16,
      s: 'Data-structure-heavy designs: LRU Cache, Rate Limiter, Splitwise, Chess.',
      learn: ['LRU / LFU cache', 'Rate limiter', 'Splitwise / expense sharing', 'Snake & Ladder / Chess'],
      tools: ['Patterns + DS'],
      proj: 'Design + code Splitwise with clean settlement logic.',
      res: [{ t: 'awesome-low-level-design', u: 'https://github.com/ashishps1/awesome-low-level-design' }, { t: 'LeetCode: LRU Cache', u: 'https://leetcode.com/problems/lru-cache/' }],
      deps: ['test', 'machine'] },
    { id: 'concheavy', t: 'Concurrency-Heavy Designs', x: 800, y: 1485, lv: 'A', h: 12,
      s: 'Designs where thread-safety is the whole challenge.',
      learn: ['Logging framework', 'Notification/dispatcher system', 'Thread-safe cache + connection pool', 'Task scheduler'],
      tools: ['Concurrency primitives'],
      proj: 'Design a thread-safe logging framework with levels + sinks.',
      res: [{ t: 'Jenkov: Java Concurrency', u: 'https://jenkov.com/tutorials/java-concurrency/index.html' }, { t: 'awesome-low-level-design', u: 'https://github.com/ashishps1/awesome-low-level-design' }],
      deps: ['prob1', 'prob2'] },
    { id: 'cap', t: 'Capstone: Full LLD', x: 800, y: 1640, lv: 'A', h: 18,
      s: 'One complete, extensible design with patterns, tests, and a clean API.',
      learn: ['Pick a non-trivial system (Uber/Swiggy)', 'Entities + patterns + concurrency', 'Tests + extensibility', 'Write up your decisions'],
      tools: ['Everything above'],
      proj: 'Design + build a ride-hailing LLD with tests + a README.',
      res: [{ t: 'awesome-low-level-design', u: 'https://github.com/ashishps1/awesome-low-level-design' }, { t: 'GitHub (publish)', u: 'https://github.com/' }],
      deps: ['concheavy'] },
  ],
};
