import type { Track } from './types';

// AI tracks: from-scratch, SWE fast-path, and advanced/production.
// res items are { t: label, u: url } — real, canonical links.

export const scratch: Track = {
  id: 'scratch',
  name: 'ML → Agentic AI (from scratch)',
  emoji: '🌱',
  blurb: 'Zero background to building AI agents. Math + ML + deep learning + LLMs + agents. Part-time over 9–12 months.',
  nodes: [
    { id: 'py', t: 'Python for ML', x: 800, y: 90, lv: 'F', h: 40,
      s: 'The language everything else is written in. Get fluent before touching math or models.',
      learn: ['Syntax, data structures, functions, OOP basics', 'Virtual envs, pip, notebooks (Jupyter/Colab)', 'NumPy arrays and vectorized thinking', 'Pandas dataframes, matplotlib plots'],
      tools: ['Python 3', 'Jupyter', 'NumPy', 'Pandas', 'Matplotlib'],
      proj: 'Load a CSV, clean it, and plot 3 insights with pandas + matplotlib.',
      res: [{ t: 'freeCodeCamp: Python (4h video)', u: 'https://www.youtube.com/watch?v=rfscVS0vtbw' }, { t: 'Kaggle: Python course', u: 'https://www.kaggle.com/learn/python' }, { t: 'NumPy quickstart', u: 'https://numpy.org/doc/stable/user/quickstart.html' }],
      deps: [] },
    { id: 'math', t: 'Math for ML', x: 800, y: 245, lv: 'F', h: 60,
      s: 'The intuition behind every model: linear algebra, calculus, probability, statistics.',
      learn: ['Vectors, matrices, dot products, matrix multiply', 'Derivatives, gradients, chain rule (for backprop)', 'Probability, distributions, Bayes', 'Descriptive + inferential statistics'],
      tools: ['NumPy', '3Blue1Brown', 'Khan Academy'],
      proj: 'Implement linear regression with gradient descent from scratch in NumPy.',
      res: [{ t: '3B1B: Essence of Linear Algebra', u: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab' }, { t: '3B1B: Essence of Calculus', u: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr' }, { t: 'Mathematics for ML (free book)', u: 'https://mml-book.github.io/' }, { t: 'StatQuest (stats)', u: 'https://www.youtube.com/@statquest' }],
      deps: ['py'] },
    { id: 'data', t: 'Data Wrangling & EDA', x: 585, y: 405, lv: 'F', h: 25,
      s: 'Real data is messy. Cleaning and exploring it well is half of applied ML.',
      learn: ['Missing values, outliers, types, encoding', 'Feature scaling and normalization', 'Exploratory data analysis (EDA)', 'Train/validation/test splits'],
      tools: ['Pandas', 'seaborn', 'scikit-learn'],
      proj: 'Full EDA notebook on a Kaggle dataset with cleaning + visual story.',
      res: [{ t: 'Kaggle: Pandas', u: 'https://www.kaggle.com/learn/pandas' }, { t: 'Kaggle: Data Cleaning', u: 'https://www.kaggle.com/learn/data-cleaning' }, { t: 'Hands-On ML code (Géron)', u: 'https://github.com/ageron/handson-ml3' }],
      deps: ['math'] },
    { id: 'cml', t: 'Classical ML', x: 1015, y: 405, lv: 'C', h: 50,
      s: 'Supervised and unsupervised learning with scikit-learn. The workhorse of real ML jobs.',
      learn: ['Linear/logistic regression, kNN, SVM, decision trees, random forests, gradient boosting', 'Clustering (k-means), PCA', 'Overfitting, bias–variance, regularization', 'sklearn Pipeline and workflow'],
      tools: ['scikit-learn', 'XGBoost'],
      proj: 'Train + compare 3 classifiers on Titanic; report metrics honestly.',
      res: [{ t: 'Andrew Ng: ML Specialization', u: 'https://www.coursera.org/specializations/machine-learning-introduction' }, { t: 'Hands-On ML (Géron) code', u: 'https://github.com/ageron/handson-ml3' }, { t: 'StatQuest: ML playlist', u: 'https://www.youtube.com/playlist?list=PLblh5JKOoLUICTaGLRoHQDuF_7q2GfuJF' }],
      deps: ['data', 'math'] },
    { id: 'eval', t: 'Model Evaluation & Tuning', x: 800, y: 560, lv: 'C', h: 20,
      s: 'Knowing whether a model is actually good, and making it better without fooling yourself.',
      learn: ['Accuracy, precision/recall, F1, ROC-AUC', 'Cross-validation, data leakage', 'Hyperparameter search (grid/random)', 'Confusion matrix reading'],
      tools: ['scikit-learn', 'Optuna'],
      proj: 'Add cross-validation + hyperparameter tuning to your classifier and log the gains.',
      res: [{ t: 'sklearn: model evaluation', u: 'https://scikit-learn.org/stable/modules/model_evaluation.html' }, { t: 'StatQuest: ROC & AUC', u: 'https://www.youtube.com/watch?v=4jRBRDbJemM' }],
      deps: ['cml'] },
    { id: 'nn', t: 'Neural Networks', x: 800, y: 715, lv: 'C', h: 30,
      s: 'The building block of deep learning: perceptrons, activations, and backpropagation.',
      learn: ['Perceptron, layers, activation functions', 'Forward + backward propagation', 'Loss functions, gradient descent, optimizers', 'Why depth helps'],
      tools: ['NumPy', 'micrograd'],
      proj: "Build a tiny neural net from scratch (à la Karpathy's micrograd).",
      res: [{ t: 'Karpathy: micrograd (video)', u: 'https://www.youtube.com/watch?v=VMj-3S1tku0' }, { t: 'Karpathy: Zero to Hero', u: 'https://karpathy.ai/zero-to-hero.html' }, { t: '3B1B: Neural Networks', u: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi' }],
      deps: ['eval'] },
    { id: 'torch', t: 'PyTorch', x: 585, y: 870, lv: 'C', h: 25,
      s: 'The framework you will actually train models in. Pick one and go deep — PyTorch.',
      learn: ['Tensors, autograd, nn.Module', 'Training loops, optimizers, schedulers', 'Datasets/DataLoaders, GPU basics', 'Saving/loading checkpoints'],
      tools: ['PyTorch', 'torchvision', 'Colab GPU'],
      proj: 'Reimplement your from-scratch net in PyTorch and train it on MNIST.',
      res: [{ t: 'PyTorch: official tutorials', u: 'https://pytorch.org/tutorials/' }, { t: 'learnpytorch.io', u: 'https://www.learnpytorch.io/' }],
      deps: ['nn'] },
    { id: 'cnn', t: 'CNNs (Computer Vision)', x: 1015, y: 870, lv: 'C', h: 25,
      s: 'Convolutional nets for images — the first place deep learning went mainstream.',
      learn: ['Convolutions, pooling, feature maps', 'Classic architectures (ResNet)', 'Data augmentation', 'Transfer learning / fine-tuning'],
      tools: ['PyTorch', 'torchvision'],
      proj: 'Fine-tune a pretrained ResNet on a small image dataset.',
      res: [{ t: 'Stanford CS231n notes', u: 'https://cs231n.github.io/' }, { t: 'fast.ai: Practical Deep Learning', u: 'https://course.fast.ai/' }],
      deps: ['nn'] },
    { id: 'seq', t: 'Sequence Models', x: 800, y: 1025, lv: 'C', h: 15,
      s: 'RNNs and LSTMs — the pre-transformer way to model sequences. Learn the intuition, then move on.',
      learn: ['RNN/LSTM/GRU basics and their limits', 'Word embeddings (word2vec)', 'Why long-range context was hard', 'Sets up why attention won'],
      tools: ['PyTorch'],
      proj: 'Train a small LSTM text generator, then note where it struggles.',
      res: [{ t: 'Colah: Understanding LSTMs', u: 'https://colah.github.io/posts/2015-08-Understanding-LSTMs/' }, { t: 'Karpathy: RNN Effectiveness', u: 'https://karpathy.github.io/2015/05/21/rnn-effectiveness/' }],
      deps: ['torch', 'cnn'] },
    { id: 'tf', t: 'Transformers & Attention', x: 800, y: 1180, lv: 'A', h: 30,
      s: 'The architecture behind every modern LLM. Understand attention deeply.',
      learn: ['Tokens, embeddings, positional encoding', 'Self-attention + multi-head attention', 'Encoder/decoder, the full block', 'Why transformers scale'],
      tools: ['PyTorch', 'Hugging Face'],
      proj: 'Build a small GPT following Karpathy nanoGPT / makemore.',
      res: [{ t: 'Karpathy: Let’s build GPT (video)', u: 'https://www.youtube.com/watch?v=kCc8FmEb1nY' }, { t: 'The Illustrated Transformer', u: 'https://jalammar.github.io/illustrated-transformer/' }, { t: 'Attention Is All You Need', u: 'https://arxiv.org/abs/1706.03762' }],
      deps: ['seq'] },
    { id: 'llm', t: 'LLM Fundamentals', x: 800, y: 1335, lv: 'A', h: 20,
      s: 'How large language models are trained, aligned, and controlled at inference time.',
      learn: ['Pretraining, fine-tuning, RLHF/DPO at a high level', 'Tokenization, context window, sampling (temperature, top-p)', 'Prompting basics, in-context learning', 'Capabilities and failure modes / hallucination'],
      tools: ['Hugging Face', 'tiktoken', 'Claude / open models'],
      proj: 'Run an open model locally + call a hosted LLM API; compare outputs.',
      res: [{ t: 'Hugging Face: LLM Course', u: 'https://huggingface.co/learn/llm-course' }, { t: 'Karpathy: Intro to LLMs (1h)', u: 'https://www.youtube.com/watch?v=zjkBMFhNj_g' }, { t: 'Anthropic docs', u: 'https://docs.anthropic.com/' }],
      deps: ['tf'] },
    { id: 'pe', t: 'Prompt Engineering', x: 800, y: 1490, lv: 'C', h: 10,
      s: 'Steering an LLM reliably: system prompts, examples, structure, and reasoning.',
      learn: ['System vs user prompts, roles', 'Few-shot examples, chain-of-thought', 'Output formatting + structured outputs', 'Prompt iteration and testing'],
      tools: ['Claude', 'OpenAI', 'prompt playgrounds'],
      proj: 'Turn a vague task into a robust, tested prompt with structured JSON output.',
      res: [{ t: 'Anthropic: Prompt engineering', u: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview' }, { t: 'DeepLearning.AI: Prompt Eng for Devs', u: 'https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/' }],
      deps: ['llm'] },
    { id: 'apis', t: 'LLM APIs & App Basics', x: 800, y: 1645, lv: 'C', h: 15,
      s: 'Wire an LLM into an actual app: SDKs, streaming, tool calling, cost.',
      learn: ['Chat completions + streaming', 'Function / tool calling, structured outputs', 'Prompt caching, tokens + cost', 'Basic app skeleton (API + UI)'],
      tools: ['Anthropic SDK', 'Next.js', 'Vercel AI SDK'],
      proj: 'Ship a small chat app with streaming + one tool call.',
      res: [{ t: 'Anthropic: API docs', u: 'https://docs.anthropic.com/en/api/overview' }, { t: 'Vercel AI SDK', u: 'https://ai-sdk.dev/docs/introduction' }],
      deps: ['pe'] },
    { id: 'rag', t: 'RAG', x: 585, y: 1800, lv: 'A', h: 25,
      s: 'Ground an LLM in your own data with retrieval-augmented generation.',
      learn: ['Embeddings + vector similarity', 'Chunking strategies', 'Vector DBs, retrieval, reranking', 'Citations + reducing hallucination'],
      tools: ['pgvector', 'Chroma', 'Qdrant', 'LlamaIndex'],
      proj: 'Build a "chat with your PDFs" app with citations.',
      res: [{ t: 'LlamaIndex docs', u: 'https://docs.llamaindex.ai/' }, { t: 'Pinecone: learning center', u: 'https://www.pinecone.io/learn/' }, { t: 'Anthropic: Contextual Retrieval', u: 'https://www.anthropic.com/news/contextual-retrieval' }],
      deps: ['apis'] },
    { id: 'agents', t: 'AI Agents', x: 1015, y: 1800, lv: 'A', h: 25,
      s: 'LLMs that plan, call tools in a loop, and act — the agentic core.',
      learn: ['The agent loop (observe → think → act)', 'Tool use + ReAct pattern', 'Frameworks (LangGraph, agent SDKs), MCP', 'Memory + state'],
      tools: ['LangGraph', 'MCP', 'Anthropic Agent SDK'],
      proj: 'Build a research agent that searches, reads, and writes a brief.',
      res: [{ t: 'Anthropic: Building Effective Agents', u: 'https://www.anthropic.com/research/building-effective-agents' }, { t: 'LangGraph docs', u: 'https://langchain-ai.github.io/langgraph/' }, { t: 'ReAct paper', u: 'https://arxiv.org/abs/2210.03629' }],
      deps: ['apis'] },
    { id: 'evals', t: 'Evaluation & Observability', x: 800, y: 1955, lv: 'A', h: 20,
      s: 'The skill that separates a demo from a product: measuring LLM/agent quality.',
      learn: ['Eval datasets + golden sets', 'LLM-as-judge, RAGAS, DeepEval', 'Tracing + observability', 'Regression testing on every change'],
      tools: ['RAGAS', 'DeepEval', 'LangSmith', 'Langfuse'],
      proj: 'Add an eval suite + tracing to your RAG or agent app.',
      res: [{ t: 'RAGAS docs', u: 'https://docs.ragas.io/' }, { t: 'Langfuse docs', u: 'https://langfuse.com/docs' }, { t: 'Hamel: Your AI product needs evals', u: 'https://hamel.dev/blog/posts/evals/' }],
      deps: ['rag', 'agents'] },
    { id: 'ops', t: 'MLOps & Deployment', x: 800, y: 2110, lv: 'A', h: 25,
      s: 'Ship it: cost control, latency, caching, monitoring, and safe rollout.',
      learn: ['Deployment (serverless / containers)', 'Cost + model routing, caching', 'Guardrails, rate limits, safety', 'Monitoring + feedback loops'],
      tools: ['Vercel', 'Docker', 'guardrails libraries'],
      proj: 'Deploy your app publicly with monitoring + a cost dashboard.',
      res: [{ t: 'Full Stack LLM Bootcamp', u: 'https://fullstackdeeplearning.com/llm-bootcamp/' }, { t: 'OWASP LLM Top 10', u: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/' }],
      deps: ['evals'] },
    { id: 'cap', t: 'Capstone', x: 800, y: 2265, lv: 'A', h: 40,
      s: 'One portfolio project that proves you can build, evaluate, and ship an AI system.',
      learn: ['Scope a real problem end-to-end', 'RAG + agent + evals + deploy together', 'Write it up (README, demo, tradeoffs)', 'Talk about it in interviews'],
      tools: ['Everything above'],
      proj: 'Design → build → evaluate → deploy → document one non-trivial AI product.',
      res: [{ t: 'GitHub (publish your work)', u: 'https://github.com/' }, { t: 'Vercel (deploy a live demo)', u: 'https://vercel.com/' }],
      deps: ['ops'] },
  ],
};

export const swe: Track = {
  id: 'swe',
  name: 'SWE → Agentic AI Engineer (fast path)',
  emoji: '⚡',
  blurb: 'You already code. Skip model training; go straight to building LLM apps, RAG, agents, and evals. ~8–12 weeks.',
  nodes: [
    { id: 'how', t: 'How LLMs Work (concepts)', x: 800, y: 90, lv: 'F', h: 8,
      s: 'Enough mental model to build well — no training math required.',
      learn: ['Tokens, embeddings, context window', 'Attention at a conceptual level', 'Temperature / top-p, sampling', 'Why models hallucinate + their limits'],
      tools: ['Any LLM playground'],
      proj: 'Write a one-pager explaining tokens, context, and temperature in your own words.',
      res: [{ t: 'The Illustrated Transformer', u: 'https://jalammar.github.io/illustrated-transformer/' }, { t: 'Karpathy: Intro to LLMs (1h)', u: 'https://www.youtube.com/watch?v=zjkBMFhNj_g' }],
      deps: [] },
    { id: 'sdk', t: 'LLM APIs & SDKs', x: 800, y: 245, lv: 'F', h: 12,
      s: 'Call models like any other API: requests, streaming, cost, retries.',
      learn: ['Chat + streaming responses', 'Messages API shape, system prompts', 'Tokens, pricing, latency', 'Errors, retries, timeouts'],
      tools: ['Anthropic SDK', 'OpenAI SDK', 'Vercel AI SDK'],
      proj: 'Build a streaming chat endpoint in your stack (Next.js API route).',
      res: [{ t: 'Anthropic: API docs', u: 'https://docs.anthropic.com/en/api/overview' }, { t: 'Vercel AI SDK', u: 'https://ai-sdk.dev/docs/introduction' }],
      deps: ['how'] },
    { id: 'struct', t: 'Structured Output & Tool Calling', x: 585, y: 405, lv: 'C', h: 10,
      s: 'Make model output reliable enough for code to consume, and let it call your functions.',
      learn: ['JSON mode / structured outputs + schema validation', 'Function / tool calling loop', 'Parallel tool calls, error handling', 'When to use tools vs pure text'],
      tools: ['Zod', 'JSON Schema', 'Anthropic tool use'],
      proj: 'Extract structured data from messy text with a validated schema.',
      res: [{ t: 'Anthropic: Tool use', u: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/overview' }, { t: 'AI SDK: structured data', u: 'https://ai-sdk.dev/docs/ai-sdk-core/generating-structured-data' }],
      deps: ['sdk'] },
    { id: 'prompt', t: 'Prompt Engineering', x: 1015, y: 405, lv: 'C', h: 10,
      s: 'Get consistent behavior: system design, examples, reasoning, and iteration.',
      learn: ['System prompt design', 'Few-shot + chain-of-thought', 'Output contracts + guardrail phrasing', 'Prompt versioning + testing'],
      tools: ['Prompt playgrounds', 'Anthropic console'],
      proj: 'Convert a flaky prompt into a tested, versioned prompt with examples.',
      res: [{ t: 'Anthropic: Prompt engineering', u: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview' }, { t: 'DeepLearning.AI: Prompt Eng', u: 'https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/' }],
      deps: ['sdk'] },
    { id: 'ctx', t: 'Context Engineering', x: 800, y: 560, lv: 'C', h: 10,
      s: 'The real 2026 skill: getting the right information into the window at the right time.',
      learn: ['Context window budgeting', 'Prompt caching for cost/latency', 'Summarization + compaction', 'Assembling context from many sources'],
      tools: ['Prompt caching', 'tokenizers'],
      proj: 'Add prompt caching + a context budget to your chat app; measure savings.',
      res: [{ t: 'Anthropic: Prompt caching', u: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching' }, { t: 'Anthropic: Context engineering', u: 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents' }],
      deps: ['struct', 'prompt'] },
    { id: 'emb', t: 'Embeddings & Vector DBs', x: 800, y: 715, lv: 'C', h: 12,
      s: 'Turn text into vectors and search by meaning — the foundation of RAG.',
      learn: ['Embedding models + similarity', 'Vector databases + indexes', 'Metadata filtering', 'Cost + latency of retrieval'],
      tools: ['pgvector', 'Qdrant', 'Chroma', 'Pinecone'],
      proj: 'Embed a docs set and build a semantic search endpoint.',
      res: [{ t: 'Pinecone: learning center', u: 'https://www.pinecone.io/learn/' }, { t: 'Qdrant docs', u: 'https://qdrant.tech/documentation/' }, { t: 'pgvector', u: 'https://github.com/pgvector/pgvector' }],
      deps: ['ctx'] },
    { id: 'ragp', t: 'RAG Pipeline', x: 800, y: 870, lv: 'C', h: 20,
      s: 'Ground answers in your data with citations and controlled hallucination.',
      learn: ['Chunking strategies', 'Retrieve → rank → generate flow', 'Citations + grounding', 'Handling "I don’t know"'],
      tools: ['LlamaIndex', 'LangChain', 'pgvector'],
      proj: 'Ship a "chat with your docs" app with inline citations.',
      res: [{ t: 'LlamaIndex docs', u: 'https://docs.llamaindex.ai/' }, { t: 'Anthropic: Contextual Retrieval', u: 'https://www.anthropic.com/news/contextual-retrieval' }],
      deps: ['emb'] },
    { id: 'rerank', t: 'Reranking & Hybrid Search', x: 1015, y: 1025, lv: 'A', h: 12,
      s: 'The single biggest RAG quality lever: better retrieval before generation.',
      learn: ['Keyword + vector hybrid search', 'Cross-encoder rerankers', 'Query rewriting / HyDE', 'Chunk + metadata tuning'],
      tools: ['Cohere Rerank', 'BM25', 'reciprocal rank fusion'],
      proj: 'Add hybrid search + a reranker; A/B against plain vector RAG.',
      res: [{ t: 'Cohere: Rerank', u: 'https://docs.cohere.com/docs/rerank-overview' }, { t: 'Anthropic: Contextual Retrieval', u: 'https://www.anthropic.com/news/contextual-retrieval' }],
      deps: ['ragp'] },
    { id: 'agf', t: 'Agent Fundamentals', x: 585, y: 1025, lv: 'C', h: 16,
      s: 'The agent loop: an LLM that decides, calls tools, observes, and repeats.',
      learn: ['Observe → reason → act loop', 'ReAct + tool-use patterns', 'Stopping conditions + max steps', 'Failure recovery'],
      tools: ['Anthropic Agent SDK', 'plain tool loop'],
      proj: 'Hand-roll a minimal agent loop (no framework) that uses 2 tools.',
      res: [{ t: 'Anthropic: Building Effective Agents', u: 'https://www.anthropic.com/research/building-effective-agents' }, { t: 'ReAct paper', u: 'https://arxiv.org/abs/2210.03629' }],
      deps: ['ragp'] },
    { id: 'frame', t: 'Agent Frameworks', x: 585, y: 1180, lv: 'C', h: 14,
      s: 'Graph-based orchestration so agents are debuggable and controllable.',
      learn: ['LangGraph state graphs', 'Nodes, edges, conditional routing', 'Human-in-the-loop checkpoints', 'When NOT to use a framework'],
      tools: ['LangGraph', 'LlamaIndex Workflows'],
      proj: 'Rebuild your agent as a LangGraph with a human-approval step.',
      res: [{ t: 'LangGraph docs', u: 'https://langchain-ai.github.io/langgraph/' }, { t: 'LangChain Academy', u: 'https://academy.langchain.com/' }],
      deps: ['agf'] },
    { id: 'mcp', t: 'MCP & Tool Design', x: 800, y: 1335, lv: 'C', h: 12,
      s: 'Standardized tools (MCP) and interfaces agents can use reliably.',
      learn: ['Model Context Protocol basics', 'Building + consuming MCP servers', 'Tool schemas + good descriptions', 'Errors, idempotency, safety'],
      tools: ['MCP', 'Anthropic tool use'],
      proj: 'Wrap an internal API as an MCP server and let your agent use it.',
      res: [{ t: 'Model Context Protocol', u: 'https://modelcontextprotocol.io/' }, { t: 'Anthropic: MCP', u: 'https://docs.anthropic.com/en/docs/mcp' }],
      deps: ['frame', 'rerank'] },
    { id: 'mem', t: 'Memory & State', x: 585, y: 1490, lv: 'A', h: 12,
      s: 'Give agents short- and long-term memory that survives across turns and sessions.',
      learn: ['Short-term (conversation) vs long-term memory', 'Memory retrieval + summarization', 'Persisting state (DB)', 'Avoiding context bloat'],
      tools: ['Vector store', 'MongoDB / Postgres'],
      proj: 'Add persistent memory to your agent so it recalls past sessions.',
      res: [{ t: 'LangGraph: Memory', u: 'https://langchain-ai.github.io/langgraph/concepts/memory/' }, { t: 'Mem0', u: 'https://docs.mem0.ai/' }],
      deps: ['mcp'] },
    { id: 'multi', t: 'Multi-Agent Orchestration', x: 1015, y: 1490, lv: 'A', h: 16,
      s: 'Coordinate specialized agents: supervisor, handoffs, and agent-to-agent.',
      learn: ['Supervisor + worker patterns', 'Handoffs + shared state', 'A2A protocol basics', 'When multi-agent actually helps'],
      tools: ['LangGraph', 'A2A', 'CrewAI'],
      proj: 'Build a supervisor that routes tasks to 2–3 specialist agents.',
      res: [{ t: 'Anthropic: Multi-agent research system', u: 'https://www.anthropic.com/engineering/built-multi-agent-research-system' }, { t: 'LangGraph: Multi-agent', u: 'https://langchain-ai.github.io/langgraph/concepts/multi_agent/' }],
      deps: ['mcp'] },
    { id: 'ev', t: 'Evaluation', x: 800, y: 1645, lv: 'A', h: 18,
      s: 'Only 52% of teams with prod agents have evals. Be in that half.',
      learn: ['Golden datasets + task metrics', 'LLM-as-judge + calibration', 'RAGAS / DeepEval for RAG', 'Agent trajectory + tool-call accuracy'],
      tools: ['RAGAS', 'DeepEval', 'Braintrust'],
      proj: 'Build an eval set + LLM judge; block regressions on every change.',
      res: [{ t: 'Hamel: Evals', u: 'https://hamel.dev/blog/posts/evals/' }, { t: 'RAGAS docs', u: 'https://docs.ragas.io/' }, { t: 'DeepEval docs', u: 'https://deepeval.com/docs/getting-started' }],
      deps: ['mem', 'multi'] },
    { id: 'obs', t: 'Observability & Tracing', x: 585, y: 1800, lv: 'A', h: 12,
      s: 'See inside every LLM call, retrieval, and tool step when things break.',
      learn: ['End-to-end traces (calls, retrieval, tools)', 'Latency + token dashboards', 'Debugging bad outputs from traces', 'Prod monitoring + drift alerts'],
      tools: ['LangSmith', 'Langfuse', 'Arize Phoenix', 'MLflow'],
      proj: 'Instrument your app with tracing and debug one real failure from a trace.',
      res: [{ t: 'Langfuse docs', u: 'https://langfuse.com/docs' }, { t: 'LangSmith docs', u: 'https://docs.smith.langchain.com/' }, { t: 'Arize Phoenix', u: 'https://docs.arize.com/phoenix' }],
      deps: ['ev'] },
    { id: 'guard', t: 'Guardrails & Safety', x: 1015, y: 1800, lv: 'A', h: 10,
      s: 'Guardrails now means authorizing actions, not just filtering text.',
      learn: ['Input/output validation', 'Tool authorization before action', 'Rate limits + spend caps', 'Prompt-injection basics'],
      tools: ['Guardrails AI', 'schema validation'],
      proj: 'Add authorization + spend caps around your agent’s tool calls.',
      res: [{ t: 'OWASP: LLM Top 10', u: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/' }, { t: 'Guardrails AI', u: 'https://www.guardrailsai.com/docs' }],
      deps: ['ev'] },
    { id: 'ship', t: 'Deploy, Cost & Ship', x: 800, y: 1955, lv: 'A', h: 12,
      s: 'Production reality: latency, streaming UX, model routing, and cost control.',
      learn: ['Serverless deploy (Vercel)', 'Streaming UI + optimistic UX', 'Model routing + caching for cost', 'Feedback capture'],
      tools: ['Vercel', 'AI SDK', 'Redis cache'],
      proj: 'Deploy your agent publicly with streaming UI + a cost/latency view.',
      res: [{ t: 'Vercel AI SDK', u: 'https://ai-sdk.dev/docs/introduction' }, { t: 'Vercel: deploy', u: 'https://vercel.com/docs/deployments/overview' }],
      deps: ['obs', 'guard'] },
    { id: 'capstone', t: 'Capstone', x: 800, y: 2110, lv: 'A', h: 30,
      s: 'A production-quality agentic app that shows RAG + agents + evals + deploy together.',
      learn: ['Real problem, end-to-end', 'Evals + observability baked in', 'Guardrails + cost control', 'Great README + live demo'],
      tools: ['Everything above'],
      proj: 'Build + deploy one polished agentic product and write it up.',
      res: [{ t: 'GitHub (publish)', u: 'https://github.com/' }, { t: 'Vercel (live demo)', u: 'https://vercel.com/' }],
      deps: ['ship'] },
  ],
};

export const prod: Track = {
  id: 'prod',
  name: 'Agentic Systems (advanced / production)',
  emoji: '🚀',
  blurb: 'You can build basic LLM apps. Go deep on production agents: advanced RAG, multi-agent, eval infra, ops, security.',
  nodes: [
    { id: 'loop', t: 'Agent Loop Deep Dive', x: 800, y: 90, lv: 'C', h: 12,
      s: 'Master the control flow that every agent framework hides behind abstractions.',
      learn: ['Message/state loop internals', 'Tool routing + parallelism', 'Stop conditions, budgets, retries', 'Determinism + reproducibility'],
      tools: ['Anthropic Agent SDK', 'LangGraph'],
      proj: 'Write a robust hand-rolled loop with budgets, retries, and tracing hooks.',
      res: [{ t: 'Anthropic: Building Effective Agents', u: 'https://www.anthropic.com/research/building-effective-agents' }, { t: 'LangGraph: low-level', u: 'https://langchain-ai.github.io/langgraph/concepts/low_level/' }],
      deps: [] },
    { id: 'plan', t: 'Planning & Reasoning', x: 585, y: 245, lv: 'A', h: 16,
      s: 'How agents decompose and self-correct: ReAct, plan-execute, reflection.',
      learn: ['ReAct vs Plan-and-Execute', 'Reflection + self-critique loops', 'Tree/graph-of-thought', 'Reasoning-model tradeoffs'],
      tools: ['LangGraph', 'reasoning models'],
      proj: 'Add a reflection step and measure quality vs cost.',
      res: [{ t: 'ReAct paper', u: 'https://arxiv.org/abs/2210.03629' }, { t: 'Reflexion paper', u: 'https://arxiv.org/abs/2303.11366' }],
      deps: ['loop'] },
    { id: 'tools', t: 'Tool & MCP Design', x: 1015, y: 245, lv: 'A', h: 15,
      s: 'Robust tools are the difference between a flaky demo and a dependable agent.',
      learn: ['Tool schema + description design', 'MCP servers at scale', 'Idempotency, retries, error surfaces', 'Least-privilege tool access'],
      tools: ['MCP', 'JSON Schema'],
      proj: 'Design an MCP server with strict schemas + graceful failures.',
      res: [{ t: 'Model Context Protocol', u: 'https://modelcontextprotocol.io/' }, { t: 'Anthropic: Tool use', u: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use/overview' }],
      deps: ['loop'] },
    { id: 'aret', t: 'Advanced Retrieval', x: 585, y: 400, lv: 'A', h: 18,
      s: 'Squeeze real quality out of RAG: hybrid, rerank, query transforms.',
      learn: ['Hybrid (BM25 + vector) + fusion', 'Cross-encoder reranking', 'Query rewriting, HyDE, multi-query', 'Chunking + metadata strategy'],
      tools: ['Cohere Rerank', 'Elasticsearch', 'pgvector'],
      proj: 'Build a retrieval eval harness and tune to a target recall.',
      res: [{ t: 'Cohere: Rerank', u: 'https://docs.cohere.com/docs/rerank-overview' }, { t: 'LlamaIndex: advanced retrieval', u: 'https://docs.llamaindex.ai/en/stable/optimizing/production_rag/' }],
      deps: ['plan'] },
    { id: 'cret', t: 'Contextual & Parent-Doc Retrieval', x: 585, y: 555, lv: 'A', h: 14,
      s: 'Retrieval patterns that preserve meaning and context around each chunk.',
      learn: ['Contextual retrieval (prepend context)', 'Parent-document + small-to-big', 'Sentence-window retrieval', 'Late chunking'],
      tools: ['LlamaIndex', 'Anthropic contextual retrieval'],
      proj: 'Add contextual retrieval and measure the recall/precision lift.',
      res: [{ t: 'Anthropic: Contextual Retrieval', u: 'https://www.anthropic.com/news/contextual-retrieval' }, { t: 'LlamaIndex docs', u: 'https://docs.llamaindex.ai/' }],
      deps: ['aret'] },
    { id: 'graph', t: 'Graph RAG & Knowledge Graphs', x: 585, y: 710, lv: 'A', h: 16,
      s: 'When relationships matter more than similarity, use a graph.',
      learn: ['Knowledge graph construction', 'GraphRAG retrieval', 'Entity + relation extraction', 'Hybrid graph + vector'],
      tools: ['Neo4j', 'GraphRAG', 'LlamaIndex KG'],
      proj: 'Build a GraphRAG over a corpus and compare to vector RAG.',
      res: [{ t: 'Microsoft GraphRAG', u: 'https://microsoft.github.io/graphrag/' }, { t: 'Neo4j: GenAI', u: 'https://neo4j.com/labs/genai-ecosystem/' }],
      deps: ['cret'] },
    { id: 'aragc', t: 'Agentic RAG', x: 800, y: 865, lv: 'A', h: 16,
      s: 'Let the agent decide when + how to retrieve, and re-retrieve on the fly.',
      learn: ['Retrieval as a tool', 'Self-RAG / corrective RAG', 'Multi-hop retrieval', 'Grounding + citation enforcement'],
      tools: ['LangGraph', 'LlamaIndex'],
      proj: 'Build an agent that iteratively retrieves until it can cite an answer.',
      res: [{ t: 'Self-RAG paper', u: 'https://arxiv.org/abs/2310.11511' }, { t: 'Corrective RAG paper', u: 'https://arxiv.org/abs/2401.15884' }],
      deps: ['graph', 'tools'] },
    { id: 'msys', t: 'Memory Systems', x: 1015, y: 400, lv: 'A', h: 16,
      s: 'Episodic, semantic, and working memory that make agents feel persistent.',
      learn: ['Memory types + when to use each', 'Write/read/forget policies', 'Memory retrieval + summarization', 'Personalization + privacy'],
      tools: ['Vector store', 'MongoDB', 'Zep / Mem0'],
      proj: 'Design a memory layer with retrieval + decay; test recall over sessions.',
      res: [{ t: 'Mem0 docs', u: 'https://docs.mem0.ai/' }, { t: 'Zep docs', u: 'https://help.getzep.com/' }],
      deps: ['tools'] },
    { id: 'msa', t: 'Multi-Agent Systems', x: 1015, y: 555, lv: 'A', h: 18,
      s: 'Supervisors, swarms, and agent-to-agent protocols done reliably.',
      learn: ['Supervisor/worker + swarm patterns', 'A2A protocol + handoffs', 'Shared state + conflict handling', 'Cost/latency of many agents'],
      tools: ['LangGraph', 'A2A', 'CrewAI', 'AutoGen'],
      proj: 'Build a supervisor orchestrating specialists with shared state.',
      res: [{ t: 'Anthropic: Multi-agent research', u: 'https://www.anthropic.com/engineering/built-multi-agent-research-system' }, { t: 'A2A protocol', u: 'https://a2a-protocol.org/' }],
      deps: ['msys'] },
    { id: 'ctxs', t: 'Context Engineering at Scale', x: 1015, y: 710, lv: 'A', h: 14,
      s: 'Right context, right agent, right time — from a single source of truth.',
      learn: ['Context routing per agent', 'Compaction + hierarchical summaries', 'Prompt caching at scale', 'Governance of shared context'],
      tools: ['Prompt caching', 'vector store'],
      proj: 'Add per-agent context routing + caching; measure token savings.',
      res: [{ t: 'Anthropic: Context engineering', u: 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents' }, { t: 'Anthropic: Prompt caching', u: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching' }],
      deps: ['msa'] },
    { id: 'evinf', t: 'Eval Infrastructure', x: 800, y: 1020, lv: 'A', h: 18,
      s: 'Three tiers: fast PR checks, nightly regression, prod monitoring.',
      learn: ['Golden sets + dataset versioning', 'CI evals on every PR', 'Nightly regression suites', 'Continuous prod eval + drift alerts'],
      tools: ['Braintrust', 'RAGAS', 'DeepEval', 'MLflow'],
      proj: 'Wire a 3-tier eval pipeline into CI for one agent.',
      res: [{ t: 'Braintrust docs', u: 'https://www.braintrust.dev/docs' }, { t: 'RAGAS docs', u: 'https://docs.ragas.io/' }],
      deps: ['aragc', 'ctxs'] },
    { id: 'judge', t: 'LLM-as-Judge & Calibration', x: 585, y: 1175, lv: 'A', h: 14,
      s: 'A judge you have not calibrated is just another unverified opinion.',
      learn: ['Judge prompt design', 'Pairwise vs pointwise scoring', 'Aligning judges to human labels', 'Bias + variance in judges'],
      tools: ['LLM judge', 'MLflow', 'human labels'],
      proj: 'Calibrate an LLM judge against human ratings; report agreement.',
      res: [{ t: 'MLflow: LLM-as-judge', u: 'https://mlflow.org/docs/latest/genai/eval-monitor/' }, { t: 'Judging LLM-as-a-Judge (paper)', u: 'https://arxiv.org/abs/2306.05685' }],
      deps: ['evinf'] },
    { id: 'traj', t: 'Agent Trajectory Evals', x: 1015, y: 1175, lv: 'A', h: 14,
      s: 'Evaluate the path, not just the answer: tool calls, steps, and task success.',
      learn: ['Task completion metrics', 'Tool-call accuracy + order', 'Trajectory + step-level scoring', 'Failure taxonomy'],
      tools: ['LangSmith', 'DeepEval', 'custom harness'],
      proj: 'Score agent trajectories on a task suite and find the top failure mode.',
      res: [{ t: 'LangSmith: agent evals', u: 'https://docs.smith.langchain.com/evaluation' }, { t: 'DeepEval docs', u: 'https://deepeval.com/docs/getting-started' }],
      deps: ['evinf'] },
    { id: 'gov', t: 'Guardrails & Governance', x: 800, y: 1330, lv: 'A', h: 14,
      s: 'The control layer: policy, approvals, and human-in-the-loop, made explainable.',
      learn: ['Authorization at tool-execution layer', 'Human approval gates', 'Policy checks + audit trails', 'Rate limits + spend governance'],
      tools: ['Guardrails AI', 'policy engines'],
      proj: 'Add policy checks + human approval + an audit log to an agent.',
      res: [{ t: 'Guardrails AI', u: 'https://www.guardrailsai.com/docs' }, { t: 'OWASP: LLM Top 10', u: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/' }],
      deps: ['judge', 'traj'] },
    { id: 'cost', t: 'Cost, Routing & Caching', x: 585, y: 1485, lv: 'A', h: 14,
      s: 'Make it cheap and fast enough to run in production at scale.',
      learn: ['Model routing (small→large)', 'Prompt + semantic caching', 'Batching + parallelism', 'Token + spend budgets'],
      tools: ['Router libs', 'Redis', 'prompt caching'],
      proj: 'Add routing + caching; cut cost per task by a measured %.',
      res: [{ t: 'Anthropic: Prompt caching', u: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching' }, { t: 'Anthropic: Message Batches', u: 'https://docs.anthropic.com/en/docs/build-with-claude/batch-processing' }],
      deps: ['gov'] },
    { id: 'ft', t: 'Fine-tuning & Distillation', x: 1015, y: 1485, lv: 'A', h: 18,
      s: 'When prompting hits a wall: LoRA, distillation, and preference tuning.',
      learn: ['When fine-tuning actually pays off', 'LoRA / QLoRA basics', 'Distillation (big→small)', 'RLHF / DPO overview'],
      tools: ['Hugging Face PEFT', 'Unsloth', 'Axolotl'],
      proj: 'Fine-tune a small model with LoRA on a narrow task; compare vs prompting.',
      res: [{ t: 'Hugging Face: PEFT', u: 'https://huggingface.co/docs/peft' }, { t: 'Unsloth', u: 'https://github.com/unslothai/unsloth' }],
      deps: ['gov'] },
    { id: 'opsx', t: 'Observability & Ops', x: 800, y: 1640, lv: 'A', h: 14,
      s: 'Run agents like real infra: traces, dashboards, alerts, on-call.',
      learn: ['Full-stack tracing (LLM+RAG+tools)', 'SLOs, alerting, drift detection', 'Versioning prompts + models', 'Incident playbooks'],
      tools: ['Langfuse', 'Arize', 'MLflow', 'OpenTelemetry'],
      proj: 'Stand up dashboards + alerts for latency, cost, and quality drift.',
      res: [{ t: 'Langfuse docs', u: 'https://langfuse.com/docs' }, { t: 'Arize Phoenix', u: 'https://docs.arize.com/phoenix' }],
      deps: ['cost', 'ft'] },
    { id: 'sec', t: 'Security', x: 800, y: 1795, lv: 'A', h: 14,
      s: 'Agents that act are an attack surface: injection, leakage, sandboxing.',
      learn: ['Prompt injection + tool abuse', 'Data leakage + PII handling', 'Sandboxing + least privilege', 'Supply-chain of tools/MCP'],
      tools: ['Sandboxes', 'OWASP LLM Top 10'],
      proj: 'Red-team your agent for injection + add sandboxing and allowlists.',
      res: [{ t: 'OWASP: LLM Top 10', u: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/' }, { t: 'Simon Willison: prompt injection', u: 'https://simonwillison.net/series/prompt-injection/' }],
      deps: ['opsx'] },
    { id: 'pcap', t: 'Capstone: Production Multi-Agent', x: 800, y: 1950, lv: 'A', h: 40,
      s: 'A reliable, observable, secured multi-agent system with real evals.',
      learn: ['Multi-agent + advanced RAG', '3-tier evals + observability', 'Guardrails + security', 'Cost/latency budgets met'],
      tools: ['Everything above'],
      proj: 'Design → build → evaluate → secure → deploy a production multi-agent system.',
      res: [{ t: 'GitHub (publish)', u: 'https://github.com/' }, { t: 'Anthropic: Building Effective Agents', u: 'https://www.anthropic.com/research/building-effective-agents' }],
      deps: ['sec'] },
  ],
};
